version: '1.0.{build}'
image: Visual Studio 2019
build:
  verbosity: minimal
branches:
  only:
  - master
install:
  - dotnet tool install -g dotnet-stryker
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./eroller/eroller.sln
after_test:
  - cmd: cd ./eroller/eroller.tests
  - cmd: dotnet stryker
